import {useEffect,useMemo,useState} from "react"
import {Link,useSearchParams} from "react-router-dom"
import {useAuth} from "../context/useAuth"
import {api} from "../api/client"
import AIResultPanel from "../components/AIResultPanel"
import {parameterLabel,normalizeParameters} from "../utils/parameters"
function formatDate(d){return new Date(d).toLocaleDateString(undefined,{dateStyle:"medium"})}
function formatChange(a,b){if(a===null||b===null)return "—";const d=b-a;if(d===0)return "No change";const r=Math.round(Math.abs(d)*100)/100;return d>0?`+${r}`:`-${r}`}
function Compare(){
 const{token}=useAuth();const[searchParams]=useSearchParams();const[summaries,setSummaries]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[aId,setAId]=useState("");const[bId,setBId]=useState("");const[a,setA]=useState(null);const[b,setB]=useState(null);const[detailLoading,setDetailLoading]=useState(false)
 useEffect(()=>{let c=false;(async()=>{try{const d=await api.listReports(token);d.sort((x,y)=>new Date(y.uploaded_at)-new Date(x.uploaded_at));if(!c){setSummaries(d);const p=searchParams.get("report");if(p&&d.some(r=>String(r.id)===p)){setBId(p);const o=d.find(r=>String(r.id)!==p);if(o)setAId(String(o.id))}else if(d.length>=2){setAId(String(d[1].id));setBId(String(d[0].id))}}}catch(e){if(!c)setError(e.message)}finally{if(!c)setLoading(false)}})();return()=>{c=true}},[token])
 useEffect(()=>{let c=false;if(!aId||!bId){setA(null);setB(null);return}setDetailLoading(true);Promise.all([api.getReport(token,aId),api.getReport(token,bId)]).then(([x,y])=>{if(!c){setA(x);setB(y)}}).catch(e=>{if(!c)setError(e.message)}).finally(()=>{if(!c)setDetailLoading(false)});return()=>{c=true}},[token,aId,bId])
 const[older,newer]=useMemo(()=>!a||!b?[null,null]:new Date(a.uploaded_at)<=new Date(b.uploaded_at)?[a,b]:[b,a],[a,b])
 const rows=useMemo(()=>{if(!older||!newer)return[];const x=normalizeParameters(older.extracted_parameters),y=normalizeParameters(newer.extracted_parameters);return Array.from(new Set([...Object.keys(x),...Object.keys(y)])).sort().map(k=>({key:k,old:x[k]?.value??null,new:y[k]?.value??null,unit:y[k]?.unit??x[k]?.unit??null}))},[older,newer])
 if(loading)return <div className="page-loading">Loading reports...</div>
 if(summaries.length<2)return <div className="page-container"><div className="page-header"><div><div className="eyebrow">Report history</div><h1>Compare reports</h1></div></div><div className="card empty-state"><h2>You need two reports</h2><p>Upload at least two blood reports before comparing changes between them.</p><Link to="/upload" className="btn btn-primary">Upload another report</Link></div></div>
 return <div className="page-container page-container-wide"><div className="page-header"><div className="page-header-copy"><div className="eyebrow">Report history</div><h1>Compare reports</h1><p>Review numerical changes between two uploaded reports.</p></div></div>{error&&<p className="form-error">{error}</p>}
  <div className="card compare-card"><div className="compare-selectors"><div className="form-field"><label htmlFor="report-a">Report A</label><select id="report-a" value={aId} onChange={e=>setAId(e.target.value)}>{summaries.map(r=><option key={r.id} value={r.id}>{r.filename} · {formatDate(r.uploaded_at)}</option>)}</select></div><div className="form-field"><label htmlFor="report-b">Report B</label><select id="report-b" value={bId} onChange={e=>setBId(e.target.value)}>{summaries.map(r=><option key={r.id} value={r.id}>{r.filename} · {formatDate(r.uploaded_at)}</option>)}</select></div></div></div>
  {detailLoading?<p className="page-loading">Loading comparison...</p>:older&&newer&&aId!==bId&&<><div className="section-heading" style={{marginTop:26}}><h2>Parameter changes</h2><span style={{fontSize:11,color:"var(--muted)"}}>{formatDate(older.uploaded_at)} → {formatDate(newer.uploaded_at)}</span></div><div className="card table-card"><table className="parameter-table"><thead><tr><th>Parameter</th><th>Older</th><th>Newer</th><th>Change</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td className="parameter-name">{parameterLabel(r.key)}</td><td>{r.old===null?"—":`${r.old}${r.unit?` ${r.unit}`:""}`}</td><td>{r.new===null?"—":`${r.new}${r.unit?` ${r.unit}`:""}`}</td><td>{formatChange(r.old,r.new)}</td></tr>)}</tbody></table></div><div className="disclaimer">This comparison shows numerical changes between two reports for educational purposes. It does not diagnose any condition.</div><div className="ai-section"><AIResultPanel key={`${older.id}-${newer.id}`} title="AI comparison summary" buttonLabel="Summarize changes" onGenerate={async()=>{const r=await api.getComparisonSummary(token,older.id,newer.id);return r.summary}}/></div></>}
 </div>
}
export default Compare
