import {useEffect,useMemo,useState} from "react"
import {Link} from "react-router-dom"
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from "recharts"
import {useAuth} from "../context/useAuth"
import {api} from "../api/client"
import {parameterLabel,normalizeParameters} from "../utils/parameters"
function formatShortDate(d){return new Date(d).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"2-digit"})}
function Trends(){
 const{token}=useAuth();const[reports,setReports]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selectedParameter,setSelectedParameter]=useState("")
 useEffect(()=>{let cancelled=false;(async()=>{setLoading(true);setError("");try{const summaries=await api.listReports(token);const details=await Promise.all(summaries.map(r=>api.getReport(token,r.id)));details.sort((a,b)=>new Date(a.uploaded_at)-new Date(b.uploaded_at));if(!cancelled)setReports(details)}catch(e){if(!cancelled)setError(e.message)}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[token])
 const available=useMemo(()=>{const counts={};for(const r of reports){for(const[k,v]of Object.entries(normalizeParameters(r.extracted_parameters))){if(v.value!==null)counts[k]=(counts[k]||0)+1}}return Object.keys(counts).filter(k=>counts[k]>=2).sort()},[reports])
 useEffect(()=>{if(!selectedParameter&&available.length)setSelectedParameter(available[0])},[available,selectedParameter])
 const data=useMemo(()=>reports.map(r=>{const e=normalizeParameters(r.extracted_parameters)[selectedParameter];if(!e||e.value===null)return null;return{date:formatShortDate(r.uploaded_at),value:e.value,unit:e.unit}}).filter(Boolean),[reports,selectedParameter])
 if(loading)return <div className="page-loading">Loading trends...</div>
 if(error)return <div className="page-container"><p className="form-error">{error}</p></div>
 return <div className="page-container page-container-wide"><div className="page-header"><div className="page-header-copy"><div className="eyebrow">Across your reports</div><h1>Parameter trends</h1><p>See how shared blood-report values have changed over time.</p></div>{reports.length>=2&&<Link to="/compare" className="btn btn-secondary">Compare reports</Link>}</div>
  {available.length===0?<div className="card empty-state"><h2>Not enough shared data yet</h2><p>Upload at least two reports with a shared parameter to see a trend.</p><Link to="/upload" className="btn btn-primary">Upload another report</Link></div>:<><div className="trend-toolbar"><div className="trends-select"><label className="form-field"><span style={{display:"block",marginBottom:7,fontSize:12,fontWeight:700}}>Parameter</span><select value={selectedParameter} onChange={e=>setSelectedParameter(e.target.value)}>{available.map(k=><option key={k} value={k}>{parameterLabel(k)}</option>)}</select></label></div><div style={{fontSize:12,color:"var(--muted)"}}>{data.length} recorded values</div></div>
  <div className="card chart-wrapper"><div className="chart-meta"><div><span>Selected parameter</span><strong>{parameterLabel(selectedParameter)}</strong></div><div><span>Latest value</span><strong>{data.length?`${data[data.length-1].value}${data[data.length-1].unit?` ${data[data.length-1].unit}`:""}`:"—"}</strong></div></div><ResponsiveContainer width="100%" height={370}><LineChart data={data} margin={{top:10,right:20,left:0,bottom:5}}><CartesianGrid strokeDasharray="3 3" stroke="#e7ece9"/><XAxis dataKey="date" stroke="#7d8984" fontSize={11}/><YAxis stroke="#7d8984" fontSize={11}/><Tooltip contentStyle={{borderRadius:10,border:"1px solid #e3e9e5",boxShadow:"0 8px 24px rgba(25,47,40,.08)"}} formatter={(value,_,props)=>props.payload.unit?`${value} ${props.payload.unit}`:value}/><Line type="monotone" dataKey="value" name={parameterLabel(selectedParameter)} stroke="#24685a" strokeWidth={2.5} dot={{r:4,fill:"#24685a",strokeWidth:0}} activeDot={{r:6}}/></LineChart></ResponsiveContainer></div><div className="disclaimer">Values are shown as extracted from your uploaded reports. A trend is not a diagnosis and should be interpreted in context with a healthcare professional.</div></>}
 </div>
}
export default Trends
